name: snakecharmer
favicon: null
layout_spectrum: 0.3224951659794897
typography_spectrum: 0.8298408924601972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9954671605955809
  lightness: 0.24373177695088089
  saturation: 0.7012072373181581
  rhythmicContrast: 0.7461998607032001
purpose: []
